version: '2.5'
services:
  mysql-container:
    platform: linux/x86_64
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=springbatch
    ports:
      - "3307:3306"
  springbatch-app:
    image: springbatch-app
    restart: always
    ports:
      - "8080:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql:/mysql-container:3306/springbatch
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      spring.jpa.properties.hibernate.dialect": org.hibernate.dialect.MySQL5Dialect
      spring.jpa.hibernate.ddl-auto": "create"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-container


